module.exports = {
  plugins: ['stylelint-scss', 'stylelint-order'],
  customSyntax: 'postcss-scss',
  rules: {
    'block-opening-brace-space-before': 'always',
    'at-rule-empty-line-before': 'always',
    'at-rule-semicolon-space-before': 'never',
    'block-no-empty': true,
    'color-no-invalid-hex': true,
    'comment-no-empty': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-colon-space-before': 'never',
    'declaration-colon-space-after': 'always',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-empty-line-before': [
      'always',
      {
        'except': ['after-declaration', 'first-nested'],
        'ignore': ['after-comment', 'inside-single-line-block'],
      },
    ],
    indentation: 2,
    'length-zero-no-unit': [
      true,
      { severity: 'warning' },
    ],
    'declaration-no-important': [
      true, { severity: 'warning' },
    ],
    linebreaks: 'unix',
    'max-empty-lines': 1,
    'no-duplicate-selectors': true,
    'no-eol-whitespace': true,
    'no-empty-first-line': true,
    'no-extra-semicolons': true,
    'no-invalid-double-slash-comments': true,
    'no-missing-end-of-source-newline': true,
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'property-no-unknown': true,
    'rule-empty-line-before': [
      'always-multi-line',
      {
        except: ['first-nested'],
        ignore: ['after-comment'],
      },
    ],
    'selector-pseudo-element-no-unknown': true,
    'shorthand-property-no-redundant-values': true,
    'string-no-newline': true,
    'string-quotes': 'double',
    'unit-no-unknown': true,
    'value-list-comma-newline-after': 'always-multi-line',
    'value-list-comma-space-after': 'always-single-line',
    'selector-combinator-space-before': 'always',
    'selector-combinator-space-after': 'always',
    'order/order': [
      'dollar-variables',
      'declarations',
      {
        type: 'rule',
        selector: '^&:\\w',
      },
      {
        type: 'rule',
        selector: '^&::(before|after)',
      },
      {
        type: 'rule',
        selector: '^&::before',
      },
      {
        type: 'rule',
        selector: '^&::after',
      },
      {
        type: 'rule',
        selector: '^&_',
      },
      {
        type: 'rule',
        selector: '^.',
      },
      'rules',
    ],
    'order/properties-order': [
      'content',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'display',
      'flex',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'text-align',
      'vertical-align',
      'flex-shrink',
      'flex-grow',
      'flex-basis',
      'gap',
      'order',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'overflow',
      'overflow-x',
      'overflow-y',
      'cursor',
      'opacity',
      'outline',
      'outline-width',
      'outline-style',
      'outline-color',
      'outline-offset',
      'pointer-events',
      'resize',
      'visibility',
      'color',
      'font',
      'font-family',
      'font-size',
      'font-style',
      'font-weight',
      'line-height',
      'text-overflow',
      'text-shadow',
      'text-wrap',
      'word-break',
      'word-wrap',
      'white-space',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-left',
      'padding-bottom',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-top',
      'border-top-width',
      'border-top-style',
      'border-top-color',
      'border-left',
      'border-left-width',
      'border-left-style',
      'border-left-color',
      'border-right',
      'border-right-width',
      'border-right-style',
      'border-right-color',
      'border-bottom',
      'border-bottom-width',
      'border-bottom-style',
      'border-bottom-color',
      'border-image',
      'border-image-slice',
      'border-image-width',
      'transition',
      'transition-duration',
      'transition-delay',
      'transition-timing-function',
      'transition-property',
      'transform',
      'transform-origin',
      'animation',
      'animation-name',
      'animation-duration',
      'animation-play-state',
      'animation-timing-function',
      'animation-delay',
      'animation-iteration-count',
      'animation-direction',
      'box-shadow',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-attachment',
      'background-position',
      'background-position-x',
      'background-position-y',
      'background-clip',
      'background-origin',
      'background-size',
      'z-index',
    ],
  },
};
